---
title: "CV"
---

<!-- Tip: export a PDF version of your CV to files/cv.pdf and link it here. -->

See (here)[https://jaimoondra.github.io/files/resume_Oct_5.pdf] for a PDF copy.
## Education and experience

- **Postdoctoral Fellow** at *Tepper School of Business, Carnegie Mellon University*, January 2026-present
- **Ph.D.**&nbsp;in Algorithms, Combinatorics and Optimization (ACO), *Georgia Tech*, 2021–2025
- **Visiting Scholar** at *Sloan School of Management, Massachusetts Institute of Technology*, Fall 2024
- **Research Scientist Intern**, *Amazon*, Seattle, Summer 2024
- **B.Tech.** in Computer Science and Engineering, *Indian Institute of Technology Delhi*, 2015–2019
- **Research Intern** at *Duke University*, Summer 2018
- **Research Intern** at *Indian Statistical Institute Bengaluru*, Summer 2017

## Awards and fellowships

- Poster on *Reusing Combinatorial Structure: Faster Iterative Projections over Submodular Base Polytopes* received honorable mention for best poster at Mixed Integer Programming (MIP) 2022; joint work with Hassan Mortagy and Swati Gupta.
- ARC-ACO fellowship at Georgia Tech for Spring 2023: this is jointly awarded by the Algorithms and Randomness Center and the Algorithms, Combinatorics, and Optimization program at Georgia Tech each year.

## Publications

See the [Publications](publications.qmd) page for the full list.

## Service

- Teaching Assistant at Georgia Tech, Spring 2023 and Spring 2024
- Paper reviews for conferences and journals including FOCS, STOC, SODA, NeurIPS, ITCS, IPCO, APPROX, ACDA, Math Programming, Operations Research, and SIDMA.
- Session co-chair on Discrete Optimization with Swati Gupta at INFORMS 2023.

## Invited Talks

- *Bridging Theory and Practice for Balancing Notions of Equity with Small Portfolios* at INFORMS (2024)
- *Graph theoretic tools for noise reduction in Quantum Approximate Optimization Algorithm (QAOA)* at TIFR (2024)
- *Balancing Notions of Equity: Trade-offs Between Fair Portfolio Sizes and Achievable Guarantees* at SODA (2025)
- *Portfolio Approximations and Fairness in Combinatorial Optimization* at
  - IIT Delhi (2024)
  - IISc Bengaluru (2025)
  - IIT Bombay (2024)
- *Portfolio Approximations and Fairness in Combinatorial Optimization* at INFORMS (2023)
- *Which $L_p$ norm is the fairest? Approximations for fair facility location across all "$p$"* at EC (2023)
- *Fairness Objectives in Facility Location Problems* at INFORMS (2022)
